name: 'Deploy Pull Request'
on:
  push:
    branches: [ main ]

jobs:
  deploy-pr:
    name: 'Deploy Pull Request'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Login
      run: docker login ...

    - name: Build Docker image
      run: docker build --tag 673109745344.dkr.ecr.us-east-1.amazonaws.com/learning:pr-${{ github.event.pull_request.number }} ...

    - name: Push Docker image
      run: docker push  --all 673109745344.dkr.ecr.us-east-1.amazonaws.com/learning
