name: 'Deploy Pull Request'
on:
  push:
    branches: [ main ]

jobs:
  deploy-pr:
    name: 'Deploy Pull Request'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: 673109745344.dkr.ecr.us-east-1.amazonaws.com
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build Docker image
      run: docker build --tag 673109745344.dkr.ecr.us-east-1.amazonaws.com/learning:pr-1540 ...

    - name: Push Docker image
      run: docker push  --all 673109745344.dkr.ecr.us-east-1.amazonaws.com/learning
